### ISSUE TITLE
Vue JS 2.0 support?

### ISSUE THREAD

**Issue by carcinocron** [fareez-ahamed/countdown-vuejs#2]
Looks like things like `coerce` were removed in VueJS 2.0.

**Comment by cdvv7788** [comment]
@fareez-ahamed coerce was removed, now it has to be computed. ready was removed, have to use mount now. https://vuejs.org/v2/guide/migration.html#ready-replaced.
I can provide a pull request if you don't have the time.

**Comment by fareez-ahamed** [comment]
Keeping the repo in sync with my blog post. So I'm not updating this. Probably will create a fork in future.
